### ISSUE TITLE
Realizar o deploy da aplicação

### ISSUE THREAD

**Issue by ronaldotpinto** [ronaldotpinto/podcastr#2]

**Comment by ronaldotpinto** [comment]
Deploy realizado na Vercel.
Link: https://podcastr-ronaldotpinto.vercel.app/

**Comment by henriquesouzadev** [comment]
@ronaldotpinto é muito complicado fazer o deploy na vercel? Estou tentando aqui e passando sufoco!

**Comment by ronaldotpinto** [comment]
Não achei muito complica, vou te passar um tutorial que usei.

https://www.notion.so/ronaldotpinto/Deploy-Podcastr-81c7f2a46b5a4bf78d3a8e7df6344d87

Em qua., 21 de jul. de 2021 18:30, Carlos Henrique ***@***.***>
escreveu:

**Comment by henriquesouzadev** [comment]
@ronaldotpinto Fiquei quase dois dias tentando fazer isso, rs.
Ontem que percebi que era só colocar o nome do repositorio na url do my-json-server! 
Obrigado pela dica! Uma dúvida, onde você conseguiu esse conteúdo do notion?

**Comment by ronaldotpinto** [comment]
Show! Que bom que deu certo.
O conteúdo foi adquirido durante o curso da Roketseat.

Em qui., 22 de jul. de 2021 13:36, Carlos Henrique ***@***.***>
escreveu:

**Comment by ronaldotpinto** [comment]
Se quiser bater um papo via Telegram, https://t.me/ronaldotpinto

Em qui., 22 de jul. de 2021 14:46, Ronaldo Pinto ***@***.***>
escreveu:
